name: Lint

on:
  push:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v1

      - name: Lint
        uses: norio-nomura/action-swiftlint@3.1.0

      - name: Lint --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict

      - name: Lint files changed in PR
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}
