name: Test

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v1

      - name: Make sure Xcode is installed
        run: ls /Applications | grep Xcode

      - name: Select Xcode 12
        run: sudo xcode-select --switch /Applications/Xcode_12.2.app

      - name: Build for macOS using xcodebuild
        run:
          xcodebuild test -scheme Horizon
